// <auto-generated />
using DesignPatterns.ChainOfResponsibility.contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignPatterns.ChainOfResponsibility.Migrations
{
    [DbContext(typeof(PizzeriaContext))]
    [Migration("20240517131702_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ingredient_name");

                    b.HasKey("Id");

                    b.ToTable("ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CookedProsciutto"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Prosciutto"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Pineapple"
                        });
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pizza_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pizza_base");

                    b.Property<string>("Dough")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pizza_dough");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_id");

                    b.HasKey("Id");

                    b.ToTable("pizza_order");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.OrderIngredient", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint")
                        .HasColumnName("ingredient_id");

                    b.HasKey("OrderId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("order_ingredient");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("receipt_cost");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("receipt");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.OrderIngredient", b =>
                {
                    b.HasOne("DesignPatterns.ChainOfResponsibility.models.Ingredient", "Ingredient")
                        .WithMany("OrderIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignPatterns.ChainOfResponsibility.models.Order", "Order")
                        .WithMany("OrderIngredients")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Receipt", b =>
                {
                    b.HasOne("DesignPatterns.ChainOfResponsibility.models.Order", "Order")
                        .WithOne("Receipt")
                        .HasForeignKey("DesignPatterns.ChainOfResponsibility.models.Receipt", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Ingredient", b =>
                {
                    b.Navigation("OrderIngredients");
                });

            modelBuilder.Entity("DesignPatterns.ChainOfResponsibility.models.Order", b =>
                {
                    b.Navigation("OrderIngredients");

                    b.Navigation("Receipt");
                });
#pragma warning restore 612, 618
        }
    }
}
